Revert "audio-kernel: Build support for parrot."
This reverts commit eae6cfeed11a8dfea836f33c9fb2178d47154b55.

Reason for revert: <compilation error: FAILED: out/target/product/canoe/obj/DLKM/wcd937x_dlkm.ko_intermediates/wcd937x_dlkm.ko>

Change-Id: Ic02133b984fe37787a890f0bf2a0f578a092c6ff