Revert "asoc: update the swr rx port configs"
This reverts commit 33e542be7e5b955ecf733df31b99a2b373ae7221.

Reason for revert: <compilation error: FAILED: out/target/product/canoe/obj/DLKM/wcd937x_dlkm.ko_intermediates/wcd937x_dlkm.ko>

Change-Id: Ib51cb4bd9cba1671f039e23754c95f5188b0ea6d